name = "rolldorado-app-com-gr"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=rolldorado-app.com.gr"
HMAC_KEY = "286ce070277124f32159003ca7ef6684da72792bbbd02ea454bc54bdbd382512"
COOKIE_NAME = "xe5"
PLAY_PATH = "play-now"
BUTTON_ID = "p484b846227893d8a087783c9310d32f5"
GATE_SALT = "938a72dc60f214f7"
